export const IPC = {
  SESSION_CREATE: 'session:create',
  SESSION_SEND: 'session:send',
  SESSION_STOP: 'session:stop',
  SESSION_RESUME: 'session:resume',
  SESSION_LIST: 'session:list',
  SESSION_MESSAGES: 'session:messages',
  SESSION_DELETE: 'session:delete',
  FOLDER_OPEN: 'folder:open',
  MCP_STATUS: 'mcp:status',
  SLASH_EXECUTE: 'slash:execute',
  SETTINGS_GET: 'settings:get',
  SETTINGS_UPDATE: 'settings:update',
  FILE_READ_BASE64: 'file:read-base64',
  PERMISSION_RESPONSE: 'session:permission-response',
  SESSION_MESSAGE: 'session:message',
  SESSION_STATUS: 'session:status',
  SESSION_PERMISSION: 'session:permission',
} as const
