export const IPC = {
  SESSION_CREATE: 'session:create',
  SESSION_SEND: 'session:send',
  SESSION_STOP: 'session:stop',
  SESSION_RESUME: 'session:resume',
  SESSION_LIST: 'session:list',
  SESSION_MESSAGES: 'session:messages',
  SESSION_DELETE: 'session:delete',
  FOLDER_OPEN: 'folder:open',
  MCP_STATUS: 'mcp:status',
  SLASH_EXECUTE: 'slash:execute',
  SETTINGS_GET: 'settings:get',
  SETTINGS_UPDATE: 'settings:update',
  FILE_READ_BASE64: 'file:read-base64',
  PERMISSION_RESPONSE: 'session:permission-response',
  QUESTION_RESPONSE: 'session:question-response',
  SESSION_SET_MODEL: 'session:set-model',
  SESSION_SET_PERMISSION_MODE: 'session:set-permission-mode',
  SESSION_SET_EFFORT: 'session:set-effort',
  SESSION_GET_INFO: 'session:get-info',
  SESSION_MESSAGE: 'session:message',
  SESSION_STATUS: 'session:status',
  SESSION_PERMISSION: 'session:permission',
  SESSION_QUESTION: 'session:question',
  SESSION_FILE_DIFFS: 'session:file-diffs',
  SESSION_FILE_STATUSES: 'session:file-statuses',
  SESSION_TITLE_UPDATED: 'session:title-updated',
  FOLDER_CHECK_GIT_STATUS: 'folder:check-git-status',
  FOLDER_LIST_PROJECTS: 'folder:list-projects',
  USAGE_STATS: 'usage:stats',
  WORKTREE_MERGE_CLEANUP: 'worktree:merge-cleanup',
  WORKTREE_DISCARD_CLEANUP: 'worktree:discard-cleanup',
  WORKTREE_INFO: 'worktree:info',
  WORKTREE_GET_USAGE: 'worktree:get-usage',
  WORKTREE_CLEANUP_ALL: 'worktree:cleanup-all',
  // Git Branch Status
  GIT_BRANCH_STATUS: 'git:branch-status',
  GIT_FETCH_COMPARE: 'git:fetch-compare',
  GIT_PULL: 'git:pull',
  GIT_STATUS_CHANGED: 'git:status-changed',
  GIT_WATCH: 'git:watch',
  // Git Graph
  GIT_GRAPH_GET_LOG: 'git:graph:get-log',
  GIT_GRAPH_GET_BRANCHES: 'git:graph:get-branches',
  GIT_GRAPH_CHECKOUT: 'git:graph:checkout',
  GIT_GRAPH_REFRESH: 'git:graph:refresh',
  // Git Commit
  GIT_COMMIT_GET_STATUS: 'git:commit:get-status',
  GIT_COMMIT_ANALYZE: 'git:commit:analyze',
  GIT_COMMIT_GENERATE_MSG: 'git:commit:generate-msg',
  GIT_COMMIT_EXECUTE: 'git:commit:execute',
  GIT_COMMIT_STAGE: 'git:commit:stage',
  GIT_COMMIT_UNSTAGE: 'git:commit:unstage',
  // Git Ops
  GIT_OPS_EXECUTE_NL: 'git:ops:execute-nl',
  GIT_OPS_CONFIRM: 'git:ops:confirm',
  GIT_OPS_GET_CONFLICTS: 'git:ops:get-conflicts',
  GIT_OPS_RESOLVE_CONFLICTS: 'git:ops:resolve-conflicts',
  GIT_OPS_APPLY_RESOLUTION: 'git:ops:apply-resolution',
  GIT_OPS_CONTINUE: 'git:ops:continue',
  // Git Events (main → renderer)
  GIT_GRAPH_UPDATED: 'git:graph:updated',
  GIT_COMMIT_PLAN_READY: 'git:commit:plan-ready',
  GIT_OPS_COMMAND_PLAN: 'git:ops:command-plan',
  GIT_OPS_CONFLICT_DETECTED: 'git:ops:conflict-detected',
  // PR Review
  GH_CHECK_STATUS: 'gh:check-status',
  GH_SET_PATH: 'gh:set-path',
  GH_LIST_REPOS: 'gh:list-repos',
  GH_LIST_PRS: 'gh:list-prs',
  GH_PR_DETAIL: 'gh:pr-detail',
  GH_POST_COMMENT: 'gh:post-comment',
  GH_POST_REVIEW: 'gh:post-review',
  GH_START_REVIEW: 'gh:start-review',
  GH_STOP_REVIEW: 'gh:stop-review',
  GH_LIST_REVIEWS: 'gh:list-reviews',
  GH_GET_REVIEW: 'gh:get-review',
  GH_DELETE_REVIEW: 'gh:delete-review',
  GH_SAVE_FINDINGS: 'gh:save-findings',
  GH_REVIEW_UPDATE: 'gh:review-update',
  GH_GET_AGENT_PROMPTS: 'gh:get-agent-prompts',
  GH_RESET_AGENT_PROMPT: 'gh:reset-agent-prompt',
  // PR Raise
  GH_RAISE_PR_INFO: 'gh:raise-pr-info',
  GH_RAISE_PR_GENERATE_DESCRIPTION: 'gh:raise-pr-generate-description',
  GH_RAISE_PR_CREATE: 'gh:raise-pr-create',
  // Plugins
  PLUGINS_LIST: 'plugins:list',
  PLUGINS_TOGGLE: 'plugins:toggle',
  // Plan Review
  FILE_READ_PLAN: 'file:read-plan',
  // Logging
  LOG_FROM_RENDERER: 'log:from-renderer',
  // AI Exploration Testing
  TEST_START_EXPLORATION: 'test:start-exploration',
  TEST_STOP_EXPLORATION: 'test:stop-exploration',
  TEST_LIST_EXPLORATIONS: 'test:list-explorations',
  TEST_GET_EXPLORATION: 'test:get-exploration',
  TEST_DELETE_EXPLORATION: 'test:delete-exploration',
  TEST_RESOLVE_E2E_PATH: 'test:resolve-e2e-path',
  TEST_READ_GENERATED_TEST: 'test:read-generated-test',
  TEST_EXPLORATION_UPDATE: 'test:exploration-update',
  TEST_SCAN_PROJECT: 'test:scan-project',
  TEST_SUGGEST_GOALS: 'test:suggest-goals',
  TEST_GOAL_SUGGESTION: 'test:goal-suggestion',
  TEST_START_BATCH: 'test:start-batch',
  // Tab Persistence
  TABS_GET: 'tabs:get',
} as const
