import { describe, expect, test } from 'bun:test'
import {
  formatReviewFindingDescriptionMarkdown,
  parseReviewFindingDescription,
} from '../../shared/review-finding-description'
import type { ReviewFinding } from '../../shared/types'
import {
  buildConversationCommentBody,
  buildReviewBody,
  getFindingMarker,
  prepareReviewPost,
} from '../gh-cli-review'

const riskFor = (severity: ReviewFinding['severity']): ReviewFinding['risk'] => {
  switch (severity) {
    case 'blocker':
      return { impact: 'critical', likelihood: 'likely', confidence: 'high', action: 'must-fix' }
    case 'high':
      return { impact: 'high', likelihood: 'possible', confidence: 'medium', action: 'should-fix' }
    case 'low':
      return { impact: 'low', likelihood: 'unknown', confidence: 'medium', action: 'optional' }
    default:
      return { impact: 'medium', likelihood: 'possible', confidence: 'medium', action: 'consider' }
  }
}

const f = (overrides: Partial<ReviewFinding>): ReviewFinding => ({
  id: overrides.id ?? 'id',
  file: overrides.file ?? 'src/x.ts',
  line: overrides.line ?? 1,
  severity: overrides.severity ?? 'medium',
  risk: overrides.risk ?? riskFor(overrides.severity ?? 'medium'),
  title: overrides.title ?? 'Title',
  description: overrides.description ?? 'Description',
  domain: overrides.domain ?? null,
  posted: overrides.posted ?? false,
  suggestion: overrides.suggestion,
})

describe('buildReviewBody', () => {
  test('no findings renders clean verdict with sha', () => {
    const body = buildReviewBody([], 'abcdef1234567')
    expect(body).toContain('## Pylon Review')
    expect(body).toContain('✅ **No issues found.**')
    expect(body).toContain('Reviewed at `abcdef1`')
    expect(body).not.toContain('Risk breakdown')
    expect(body).not.toContain('Top findings')
    expect(body.endsWith('*Generated by Pylon. Please verify findings before merging.*')).toBe(true)
  })

  test('no findings with empty sha omits the reviewed-at fragment', () => {
    const body = buildReviewBody([], '')
    expect(body).not.toContain('Reviewed at')
  })

  test('blocker findings produce blocking verdict and top-findings section', () => {
    const findings = [
      f({ id: '1', severity: 'blocker', title: 'Null deref', file: 'a.ts', line: 10 }),
      f({ id: '2', severity: 'blocker', title: 'SQLi', file: 'b.ts', line: 20 }),
      f({ id: '3', severity: 'high', title: 'Race', file: 'c.ts', line: 30 }),
      f({ id: '4', severity: 'medium', title: 'Naming', file: 'd.ts', line: 40 }),
    ]
    const body = buildReviewBody(findings, 'abc1234')
    expect(body).toContain('⚠️ **2 blocking issues** across 4 files.')
    expect(body).toContain('Posted 4 inline threads.')
    expect(body).toContain('### Needs Attention')
    expect(body).toContain('🔴 **Blocker: Null deref** · `a.ts:10`')
    expect(body).toContain('🔴 **Blocker: SQLi** · `b.ts:20`')
    expect(body).toContain('🟠 **High: Race** · `c.ts:30`')
    expect(body).toContain('Risk breakdown')
    expect(body).toContain('| 🔴 Blocker | 2 |')
    expect(body).toContain('| 🟠 High | 1 |')
    expect(body).toContain('| 🟡 Medium | 1 |')
    expect(body).not.toContain('| ⚪ Low |')
  })

  test('high-only produces items-to-review verdict', () => {
    const findings = [f({ severity: 'high', title: 'W1', file: 'a.ts', line: 1 })]
    const body = buildReviewBody(findings, '')
    expect(body).toContain('⚠️ **1 high-risk item to review** across 1 file.')
  })

  test('medium-only uses lightweight verdict without top findings', () => {
    const findings = [
      f({ id: '1', severity: 'medium', title: 'S1', file: 'a.ts', line: 1 }),
      f({ id: '2', severity: 'low', title: 'N1', file: 'a.ts', line: 2 }),
    ]
    const body = buildReviewBody(findings, '')
    expect(body).toContain('💡 **2 findings** across 1 file.')
    expect(body).not.toContain('### Top findings')
  })

  test('general findings render in their own collapsible section', () => {
    const findings = [
      f({ id: '1', severity: 'high', title: 'Inline', file: 'a.ts', line: 5 }),
      f({ id: '2', severity: 'medium', title: 'Convention drift', file: '', line: null }),
    ]
    const body = buildReviewBody(findings, '')
    expect(body).toContain('<summary><b>General notes</b> (1)</summary>')
    expect(body).toContain('#### 🟡 Medium: Convention drift')
    expect(body).toContain('Description')
  })

  test('footer adapts when there are only general findings', () => {
    const findings = [f({ severity: 'high', title: 'General', file: '', line: null })]
    const body = buildReviewBody(findings, '')
    expect(body.endsWith('*Generated by Pylon. Please verify findings before merging.*')).toBe(true)
    expect(body).not.toContain('Resolve or reply on inline threads')
  })

  test('footer mentions inline threads when inline findings exist', () => {
    const findings = [f({ severity: 'high', title: 'W', file: 'a.ts', line: 1 })]
    const body = buildReviewBody(findings, '')
    expect(body).toContain('Inline threads contain anchored findings')
  })

  test('top findings are capped at 3 highest-severity entries', () => {
    const findings = Array.from({ length: 6 }, (_, i) =>
      f({ id: String(i), severity: 'blocker', title: `C${i}`, file: 'a.ts', line: i + 1 }),
    )
    const body = buildReviewBody(findings, '')
    const matches = body.match(/🔴 \*\*Blocker: C\d+\*\*/g) ?? []
    expect(matches.length).toBe(3)
  })

  test('never contains an emdash', () => {
    const findings = [
      f({ severity: 'blocker', title: 'Issue', file: 'a.ts', line: 1 }),
      f({ severity: 'high', title: 'General', file: '', line: null }),
    ]
    const body = buildReviewBody(findings, 'abc1234')
    expect(body).not.toContain('\u2014')
  })
})

describe('review finding description formatting', () => {
  test('parses labeled descriptions into scan-friendly sections', () => {
    const sections = parseReviewFindingDescription(
      [
        'Observation: This overlap filter casts JSONB text to timestamptz on every candidate row.',
        'Why it matters: The predicate is not index-friendly and requires per-row evaluation.',
        'Suggested direction: Add a functional index or promote the values into typed columns.',
        'Needs verification: Check it against production-like sleep-history volume.',
      ].join('\n\n'),
    )

    expect(sections).toEqual([
      {
        kind: 'observation',
        label: 'Observation',
        body: 'This overlap filter casts JSONB text to timestamptz on every candidate row.',
      },
      {
        kind: 'impact',
        label: 'Why it matters',
        body: 'The predicate is not index-friendly and requires per-row evaluation.',
      },
      {
        kind: 'suggestion',
        label: 'Suggested direction',
        body: 'Add a functional index or promote the values into typed columns.',
      },
      {
        kind: 'verification',
        label: 'Needs verification',
        body: 'Check it against production-like sleep-history volume.',
      },
    ])
  })

  test('formats structured descriptions for markdown comments', () => {
    const markdown = formatReviewFindingDescriptionMarkdown(
      'Observation: The filter evaluates JSONB timestamps at query time.\n\nWhy it matters: That blocks normal index usage.',
    )

    expect(markdown).toBe(
      '**Observation:** The filter evaluates JSONB timestamps at query time.\n\n**Why it matters:** That blocks normal index usage.',
    )
  })

  test('heuristically separates older wall-of-text descriptions', () => {
    const sections = parseReviewFindingDescription(
      [
        'This overlap filter casts JSONB text to timestamptz on every candidate row.',
        'This expression is not index-friendly and requires per-row evaluation.',
        'Consider adding a functional index for sleep rows.',
        'Needs verification against production-like volume.',
      ].join(' '),
    )

    expect(sections).toEqual([
      {
        kind: 'observation',
        label: 'Observation',
        body: 'This overlap filter casts JSONB text to timestamptz on every candidate row.',
      },
      {
        kind: 'impact',
        label: 'Why it matters',
        body: 'This expression is not index-friendly and requires per-row evaluation.',
      },
      {
        kind: 'suggestion',
        label: 'Suggested direction',
        body: 'Consider adding a functional index for sleep rows.',
      },
      {
        kind: 'verification',
        label: 'Needs verification',
        body: 'Needs verification against production-like volume.',
      },
    ])
  })
})

describe('prepareReviewPost', () => {
  const diff = `diff --git a/src/app.ts b/src/app.ts
--- a/src/app.ts
+++ b/src/app.ts
@@ -1,4 +1,5 @@
 const existing = true
-const oldValue = 1
+const newValue = 2
+const added = compute()
 const tail = true
diff --git a/src/renamed.ts b/src/renamed.ts
--- a/src/renamed.ts
+++ b/src/renamed.ts
@@ -10,2 +10,2 @@
 export const name = 'pylon'
+export const enabled = true`

  test('posts valid right-side diff lines as inline comments', () => {
    const findings = [
      f({
        id: 'inline-1',
        file: 'src/app.ts',
        line: 3,
        severity: 'high',
        title: 'Check call',
        description:
          'Observation: This path still calls the expensive helper for every row.\n\nWhy it matters: It keeps the hot loop O(n) with extra work per item.\n\nSuggested direction: Cache the derived value before the loop.',
      }),
      f({
        id: 'inline-2',
        file: 'src/renamed.ts',
        line: 11,
        severity: 'blocker',
        title: 'Enabled by default',
        domain: 'security',
      }),
    ]

    const prepared = prepareReviewPost(findings, 'abcdef123', diff)

    expect(prepared.inlineFindings.map((finding) => finding.id)).toEqual(['inline-1', 'inline-2'])
    expect(prepared.summaryFindings).toEqual([])
    expect(prepared.comments).toEqual([
      {
        path: 'src/app.ts',
        line: 3,
        side: 'RIGHT',
        body: expect.stringContaining('<!-- pylon:finding id=inline-1 hash='),
      },
      {
        path: 'src/renamed.ts',
        line: 11,
        side: 'RIGHT',
        body: expect.stringContaining('<!-- pylon:finding id=inline-2 hash='),
      },
    ])
    expect(prepared.comments[1].body).toContain('### 🔴 Blocker: Enabled by default')
    expect(prepared.comments[0].body).toContain(
      '**Observation:** This path still calls the expensive helper for every row.',
    )
    expect(prepared.comments[0].body).toContain(
      '**Suggested direction:** Cache the derived value before the loop.',
    )
    expect(prepared.comments[1].body).not.toContain('Next step')
    expect(prepared.comments[1].body).not.toContain('Action ·')
    expect(prepared.comments[1].body).not.toContain('> **Risk:**')
    expect(prepared.comments[1].body).toContain(
      '<sub>Impact · critical · Likelihood · likely · Confidence · high · Focus · Security</sub>',
    )
  })

  test('renders actionable suggestion blocks with multi-line anchors when available', () => {
    const findings = [
      f({
        id: 'inline-suggestion',
        file: 'src/app.ts',
        line: 3,
        severity: 'high',
        title: 'Replace repeated work',
        suggestion: {
          body: 'const cached = compute()\nconst added = cached',
          startLine: 3,
          endLine: 4,
        },
      }),
    ]

    const prepared = prepareReviewPost(findings, 'abcdef123', diff)

    expect(prepared.comments).toEqual([
      {
        path: 'src/app.ts',
        line: 4,
        start_line: 3,
        start_side: 'RIGHT',
        side: 'RIGHT',
        body: expect.stringContaining(
          '```suggestion\nconst cached = compute()\nconst added = cached\n```',
        ),
      },
    ])
  })

  test('omits suggestion block when the requested range is not fully reviewable', () => {
    const findings = [
      f({
        id: 'invalid-suggestion',
        file: 'src/app.ts',
        line: 3,
        severity: 'high',
        title: 'Bad anchor',
        suggestion: {
          body: 'const safe = true',
          startLine: 3,
          endLine: 99,
        },
      }),
    ]

    const prepared = prepareReviewPost(findings, 'abcdef123', diff)

    expect(prepared.comments).toHaveLength(1)
    expect(prepared.comments[0].line).toBe(3)
    expect(prepared.comments[0]).not.toHaveProperty('start_line')
    expect(prepared.comments[0].body).not.toContain('```suggestion')
  })

  test('keeps unanchorable findings in the review summary', () => {
    const findings = [
      f({ id: 'valid', file: 'src/app.ts', line: 2, severity: 'high', title: 'Valid' }),
      f({ id: 'deleted', file: 'src/app.ts', line: 99, severity: 'blocker', title: 'Stale line' }),
      f({ id: 'general', file: '', line: null, severity: 'medium', title: 'General note' }),
    ]

    const prepared = prepareReviewPost(findings, '', diff)

    expect(prepared.comments).toHaveLength(1)
    expect(prepared.comments[0].path).toBe('src/app.ts')
    expect(prepared.comments[0].line).toBe(2)
    expect(prepared.summaryFindings.map((finding) => finding.id)).toEqual(['deleted', 'general'])
    expect(prepared.body).toContain('<summary><b>Findings listed in summary</b> (1)</summary>')
    expect(prepared.body).toContain('`src/app.ts:99`')
    expect(prepared.body).toContain('<summary><b>General notes</b> (1)</summary>')
  })

  test('falls back to summary-only when diff is unavailable', () => {
    const findings = [
      f({ id: 'one', file: 'src/app.ts', line: 2, severity: 'high', title: 'Cannot anchor' }),
    ]

    const prepared = prepareReviewPost(findings, '', '')

    expect(prepared.comments).toEqual([])
    expect(prepared.summaryFindings).toEqual(findings)
    expect(prepared.body).toContain('*Generated by Pylon. Please verify findings before merging.*')
    expect(prepared.body).not.toContain('Resolve or reply on inline threads')
  })

  test('finding marker is stable for equivalent content', () => {
    const first = f({ id: 'same-id', file: 'src/app.ts', line: 2, title: 'Title' })
    const second = f({ id: 'same-id', file: 'src/app.ts', line: 2, title: 'Title' })

    expect(getFindingMarker(first)).toBe(getFindingMarker(second))
  })
})

describe('buildConversationCommentBody', () => {
  test('renders a standalone PR conversation comment for one finding', () => {
    const body = buildConversationCommentBody(
      f({
        id: 'finding-1',
        file: 'src/app.ts',
        line: 12,
        severity: 'high',
        title: 'Missing empty state',
        description: 'The component renders a blank panel when the result set is empty.',
        domain: 'ux',
      }),
    )

    expect(body).toContain('## Pylon Finding')
    expect(body).toContain('### 🟠 High: Missing empty state')
    expect(body).toContain(
      '<sub>Location · `src/app.ts:12` · Focus · UX · Impact · high · Likelihood · possible · Confidence · medium</sub>',
    )
    expect(body).not.toContain('Next step')
    expect(body).not.toContain('Action ·')
    expect(body).not.toContain('> **Risk:**')
    expect(body).toContain('<!-- pylon:finding id=finding-1 hash=')
  })
})
