import { describe, expect, test } from 'bun:test'
import type { ReviewFinding } from '../../shared/types'
import {
  buildConversationCommentBody,
  buildReviewBody,
  getFindingMarker,
  prepareReviewPost,
} from '../gh-cli-review'

const f = (overrides: Partial<ReviewFinding>): ReviewFinding => ({
  id: overrides.id ?? 'id',
  file: overrides.file ?? 'src/x.ts',
  line: overrides.line ?? 1,
  severity: overrides.severity ?? 'suggestion',
  title: overrides.title ?? 'Title',
  description: overrides.description ?? 'Description',
  domain: overrides.domain ?? null,
  posted: overrides.posted ?? false,
})

describe('buildReviewBody', () => {
  test('no findings renders clean verdict with sha', () => {
    const body = buildReviewBody([], 'abcdef1234567')
    expect(body).toContain('## Pylon Review')
    expect(body).toContain('✅ **No issues found.**')
    expect(body).toContain('Reviewed at `abcdef1`')
    expect(body).not.toContain('Severity breakdown')
    expect(body).not.toContain('Top findings')
    expect(body.endsWith('*Generated by Pylon. Please verify findings before merging.*')).toBe(true)
  })

  test('no findings with empty sha omits the reviewed-at fragment', () => {
    const body = buildReviewBody([], '')
    expect(body).not.toContain('Reviewed at')
  })

  test('critical findings produce blocking verdict and top-findings section', () => {
    const findings = [
      f({ id: '1', severity: 'critical', title: 'Null deref', file: 'a.ts', line: 10 }),
      f({ id: '2', severity: 'critical', title: 'SQLi', file: 'b.ts', line: 20 }),
      f({ id: '3', severity: 'warning', title: 'Race', file: 'c.ts', line: 30 }),
      f({ id: '4', severity: 'suggestion', title: 'Naming', file: 'd.ts', line: 40 }),
    ]
    const body = buildReviewBody(findings, 'abc1234')
    expect(body).toContain('⚠️ **2 blocking issues** across 4 files.')
    expect(body).toContain('Posted 4 inline threads.')
    expect(body).toContain('### Needs Attention')
    expect(body).toContain('🔴 **Critical: Null deref** · `a.ts:10`')
    expect(body).toContain('🔴 **Critical: SQLi** · `b.ts:20`')
    expect(body).toContain('🟡 **Warning: Race** · `c.ts:30`')
    expect(body).toContain('Severity breakdown')
    expect(body).toContain('| 🔴 Critical | 2 |')
    expect(body).toContain('| 🟡 Warning | 1 |')
    expect(body).toContain('| 🔵 Suggestion | 1 |')
    expect(body).not.toContain('| ⚪ Nitpick |')
  })

  test('warning-only produces items-to-review verdict', () => {
    const findings = [f({ severity: 'warning', title: 'W1', file: 'a.ts', line: 1 })]
    const body = buildReviewBody(findings, '')
    expect(body).toContain('⚠️ **1 item to review** across 1 file.')
  })

  test('suggestion-only uses lightweight verdict without top findings', () => {
    const findings = [
      f({ id: '1', severity: 'suggestion', title: 'S1', file: 'a.ts', line: 1 }),
      f({ id: '2', severity: 'nitpick', title: 'N1', file: 'a.ts', line: 2 }),
    ]
    const body = buildReviewBody(findings, '')
    expect(body).toContain('💡 **2 suggestions** across 1 file.')
    expect(body).not.toContain('### Top findings')
  })

  test('general findings render in their own collapsible section', () => {
    const findings = [
      f({ id: '1', severity: 'warning', title: 'Inline', file: 'a.ts', line: 5 }),
      f({ id: '2', severity: 'suggestion', title: 'Convention drift', file: '', line: null }),
    ]
    const body = buildReviewBody(findings, '')
    expect(body).toContain('<summary><b>General notes</b> (1)</summary>')
    expect(body).toContain('#### 🔵 Suggestion: Convention drift')
    expect(body).toContain('Description')
  })

  test('footer adapts when there are only general findings', () => {
    const findings = [f({ severity: 'warning', title: 'General', file: '', line: null })]
    const body = buildReviewBody(findings, '')
    expect(body.endsWith('*Generated by Pylon. Please verify findings before merging.*')).toBe(true)
    expect(body).not.toContain('Resolve or reply on inline threads')
  })

  test('footer mentions inline threads when inline findings exist', () => {
    const findings = [f({ severity: 'warning', title: 'W', file: 'a.ts', line: 1 })]
    const body = buildReviewBody(findings, '')
    expect(body).toContain('Inline threads contain anchored findings')
  })

  test('top findings are capped at 3 highest-severity entries', () => {
    const findings = Array.from({ length: 6 }, (_, i) =>
      f({ id: String(i), severity: 'critical', title: `C${i}`, file: 'a.ts', line: i + 1 }),
    )
    const body = buildReviewBody(findings, '')
    const matches = body.match(/🔴 \*\*Critical: C\d+\*\*/g) ?? []
    expect(matches.length).toBe(3)
  })

  test('never contains an emdash', () => {
    const findings = [
      f({ severity: 'critical', title: 'Issue', file: 'a.ts', line: 1 }),
      f({ severity: 'warning', title: 'General', file: '', line: null }),
    ]
    const body = buildReviewBody(findings, 'abc1234')
    expect(body).not.toContain('\u2014')
  })
})

describe('prepareReviewPost', () => {
  const diff = `diff --git a/src/app.ts b/src/app.ts
--- a/src/app.ts
+++ b/src/app.ts
@@ -1,4 +1,5 @@
 const existing = true
-const oldValue = 1
+const newValue = 2
+const added = compute()
 const tail = true
diff --git a/src/renamed.ts b/src/renamed.ts
--- a/src/renamed.ts
+++ b/src/renamed.ts
@@ -10,2 +10,2 @@
 export const name = 'pylon'
+export const enabled = true`

  test('posts valid right-side diff lines as inline comments', () => {
    const findings = [
      f({ id: 'inline-1', file: 'src/app.ts', line: 3, severity: 'warning', title: 'Check call' }),
      f({
        id: 'inline-2',
        file: 'src/renamed.ts',
        line: 11,
        severity: 'critical',
        title: 'Enabled by default',
        domain: 'security',
      }),
    ]

    const prepared = prepareReviewPost(findings, 'abcdef123', diff)

    expect(prepared.inlineFindings.map((finding) => finding.id)).toEqual(['inline-1', 'inline-2'])
    expect(prepared.summaryFindings).toEqual([])
    expect(prepared.comments).toEqual([
      {
        path: 'src/app.ts',
        line: 3,
        side: 'RIGHT',
        body: expect.stringContaining('<!-- pylon:finding id=inline-1 hash='),
      },
      {
        path: 'src/renamed.ts',
        line: 11,
        side: 'RIGHT',
        body: expect.stringContaining('<!-- pylon:finding id=inline-2 hash='),
      },
    ])
    expect(prepared.comments[1].body).toContain('### 🔴 Critical: Enabled by default')
    expect(prepared.comments[1].body).toContain('> **Next step:** Address this before merging')
    expect(prepared.comments[1].body).toContain('<sub>Focus · Security</sub>')
  })

  test('keeps unanchorable findings in the review summary', () => {
    const findings = [
      f({ id: 'valid', file: 'src/app.ts', line: 2, severity: 'warning', title: 'Valid' }),
      f({ id: 'deleted', file: 'src/app.ts', line: 99, severity: 'critical', title: 'Stale line' }),
      f({ id: 'general', file: '', line: null, severity: 'suggestion', title: 'General note' }),
    ]

    const prepared = prepareReviewPost(findings, '', diff)

    expect(prepared.comments).toHaveLength(1)
    expect(prepared.comments[0].path).toBe('src/app.ts')
    expect(prepared.comments[0].line).toBe(2)
    expect(prepared.summaryFindings.map((finding) => finding.id)).toEqual(['deleted', 'general'])
    expect(prepared.body).toContain('<summary><b>Findings listed in summary</b> (1)</summary>')
    expect(prepared.body).toContain('`src/app.ts:99`')
    expect(prepared.body).toContain('<summary><b>General notes</b> (1)</summary>')
  })

  test('falls back to summary-only when diff is unavailable', () => {
    const findings = [
      f({ id: 'one', file: 'src/app.ts', line: 2, severity: 'warning', title: 'Cannot anchor' }),
    ]

    const prepared = prepareReviewPost(findings, '', '')

    expect(prepared.comments).toEqual([])
    expect(prepared.summaryFindings).toEqual(findings)
    expect(prepared.body).toContain('*Generated by Pylon. Please verify findings before merging.*')
    expect(prepared.body).not.toContain('Resolve or reply on inline threads')
  })

  test('finding marker is stable for equivalent content', () => {
    const first = f({ id: 'same-id', file: 'src/app.ts', line: 2, title: 'Title' })
    const second = f({ id: 'same-id', file: 'src/app.ts', line: 2, title: 'Title' })

    expect(getFindingMarker(first)).toBe(getFindingMarker(second))
  })
})

describe('buildConversationCommentBody', () => {
  test('renders a standalone PR conversation comment for one finding', () => {
    const body = buildConversationCommentBody(
      f({
        id: 'finding-1',
        file: 'src/app.ts',
        line: 12,
        severity: 'warning',
        title: 'Missing empty state',
        description: 'The component renders a blank panel when the result set is empty.',
        domain: 'ux',
      }),
    )

    expect(body).toContain('## Pylon Finding')
    expect(body).toContain('### 🟡 Warning: Missing empty state')
    expect(body).toContain('<sub>Location · `src/app.ts:12` · Focus · UX</sub>')
    expect(body).toContain(
      '> **Next step:** Verify this path and update the code if the behavior can occur.',
    )
    expect(body).toContain('<!-- pylon:finding id=finding-1 hash=')
  })
})
